POST http://localhost:3030/events
Content-Type: application/json

{
    "title": "testando rotas",
    "details": null ,
    "maximumAttendees": 2
}

###

POST http://localhost:3030/events/b267710c-8d56-4663-ac0e-3f8a65fe1ddf/attendee
Content-Type: application/json

{
    "name": "Caua Gomes",
    "email":"araujodev766@gmail.com"
}

### 

GET http://localhost:3030/event/b267710c-8d56-4663-ac0e-3f8a65fe1ddf
Content-Type: application/json

###

GET http://localhost:3030/attendee/4
Content-Type: application/json
