POST http://localhost:3030/events
Content-Type: application/json

{
    "title": "NWL UNITED",
    "details": null ,
    "maximumAttendees": 2
}

###

POST http://localhost:3030/events/f9c44e57-9713-468d-b03d-0d2c2cbf4e10/attendee
Content-Type: application/json

{
    "name": "Caua Gomes",
    "email":"araujodev766@gmail.com"
}

### 

GET http://localhost:3030/event/f9c44e57-9713-468d-b03d-0d2c2cbf4e10
Content-Type: application/json

###

GET http://localhost:3030/attendee/1
Content-Type: application/json
