POST http://localhost:3030/events
Content-Type: application/json

{
    "title": "TESTE 2",
    "details": null ,
    "maximumAttendees": 2
}

###

POST http://localhost:3030/events/0eeb5d63-cc5c-49b5-82ee-a4cc94d6b49d/attendee
Content-Type: application/json

{
    "name": "Daniel",
    "email":"teste6e@gmail.com"
}

### 

GET http://localhost:3030/event/0eeb5d63-cc5c-49b5-82ee-a4cc94d6b49d
Content-Type: application/json

###

GET http://localhost:3030/attendee/8/badge
Content-Type: application/json

###

GET http://localhost:3030/attendee/8/check-in
Content-Type: application/json

###

GET http://localhost:3030/events/0eeb5d63-cc5c-49b5-82ee-a4cc94d6b49d/attendees